spring.application.name=quantity-measurement-app
server.port=8081
 
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/quantitymeasurement
spring.datasource.username=root
spring.datasource.password=Scorpion#5320
 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true